Add caching in the service
We add caching in the service
instead of adding it into Controller or Minimal API or RPC because all of them deal with service

if we run the project and try to send this request:

###
GET {{baseUrl}}/api/products

We will get this response because we don't specify the size:
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Type: text/plain; charset=utf-8
Date: Thu, 13 Aug 2026 15:51:55 GMT
Server: Kestrel
Transfer-Encoding: chunked

System.InvalidOperationException: Cache entry must specify a value for Size when SizeLimit is set.
   at Microsoft.Extensions.Caching.Memory.MemoryCache.SetEntry(CacheEntry entry)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.Set[TItem](IMemoryCache cache, Object key, TItem value)
   at M01.CachingInMemory.Services.ProductService.GetProductsAsync() in C:\Users\Nour\OneDrive\Desktop\PerformanceInASP\M01.CachingInMemory\Services\ProductService.cs:line 29
   at M01.CachingInMemory.Controllers.ProductsController.Get() in C:\Users\Nour\OneDrive\Desktop\PerformanceInASP\M01.CachingInMemory\Controllers\ProductController.cs:line 15
   at lambda_method4(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Connection: close
Host: localhost:7062
User-Agent: vscode-restclient
Accept-Encoding: gzip, deflate
Cookie: .AspNetCore.Cookies=CfDJ8IA1QEl0etZEmDdGrhulrISIw9GFpf7alUUR0o3z7s7BbE584FBwuhWpped1fmtxPKd7ifrwjE6HN9B_2d62OQUpaMFN-jsWMCheYA3ykI-59GirAXy6qAx8uJLfIQD7lk2wYrLdl19-lXhaqNVe1vXdhek9luudVV9nhTYJ5YIa8o9TqcvVU5Y790COxejNIqMN4LXX73VaoavhXdafHHk17U_GxGlKdPAfCSkOhabepLENU1RwhXDFS_n6n52HH2IF5eyPkeOEjoGyy9xiurC1I_KFbGXisf9f87y9abM3MQojpLS44u5d3BPG57p4sYx0T3e0ZfS2SHtIzuCqCzdPRlPGdvPE5v2BgphUFVzqwzzd3YfAJxNrcCqdFXZO73V15OfXikwhE8Q8VJvhcO1MM5rMiZ9VwmBGpiPsANmDG1zr_u_JMOkX7X6Svyo44Otwhr9vofJ_FNoZha-6lj6GrZFbyJYQjkUj5dxpSngsonUxdS5ckc4qOrT-KTbo07uVdFdxpcd7ffO1PCsoSrozfViIG2-l-sEs3OSJS1qYEjGU7BS3hli5lsJujnw9uWideQ3egjs5q2dC4tJz-uecKKOjY-AaYbU2twv2zswxEMA1B-DA1B-drWfD4VShVEEpfMptLKPAc7AnGouoMtZHCdEPVPD6CIj-3yI_qfV3